USE [master]
GO

/****** Object:  Database [EducationTests]    Script Date: 13.02.2023 16:36:54 ******/
CREATE DATABASE [EducationTests]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EducationTests', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EducationTests.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EducationTests_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EducationTests_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EducationTests].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EducationTests] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EducationTests] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EducationTests] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EducationTests] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EducationTests] SET ARITHABORT OFF 
GO

ALTER DATABASE [EducationTests] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EducationTests] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EducationTests] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EducationTests] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EducationTests] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EducationTests] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EducationTests] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EducationTests] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EducationTests] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EducationTests] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EducationTests] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EducationTests] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EducationTests] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EducationTests] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EducationTests] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EducationTests] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EducationTests] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EducationTests] SET RECOVERY FULL 
GO

ALTER DATABASE [EducationTests] SET  MULTI_USER 
GO

ALTER DATABASE [EducationTests] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EducationTests] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EducationTests] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EducationTests] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EducationTests] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EducationTests] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EducationTests] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EducationTests] SET  READ_WRITE 
GO

