//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationTests.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public answer_table()
        {
            this.user_tests = new HashSet<user_tests>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_question { get; set; }
        public string name_answers { get; set; }
        public Nullable<bool> correct_answer { get; set; }
    
        public virtual question_table question_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_tests> user_tests { get; set; }
    }
}
