//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationTests.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tests
    {
        public int id { get; set; }
        public int id_user_score { get; set; }
        public int id_question { get; set; }
        public int id_answer { get; set; }
    
        public virtual answer_table answer_table { get; set; }
        public virtual question_table question_table { get; set; }
        public virtual user_score user_score { get; set; }
    }
}
