//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationTests.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_score
    {
        public int id { get; set; }
        public int id_user_test { get; set; }
        public string status { get; set; }
        public string progress { get; set; }
        public string date { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public int id_user { get; set; }
        public int id_test { get; set; }
    
        public virtual user_tests user_tests { get; set; }
        public virtual name_test name_test { get; set; }
    }
}
